version: 2

sources:
  - name: raw
    schema: raw_data

    tables:
      - name: bin_sponsor
      - name: program_manager
      - name: products
      - name: cards
      - name: authorisations
      - name: transactions
      